# SPDX-FileCopyrightText: 2021 Sébastien Wilmet <sebastien.wilmet@gmail.com>
# SPDX-License-Identifier: GPL-3.0-or-later
---
- name: configure git
  copy:
    src: "{{ item }}"
    dest: "~/.{{ item }}"
    owner: "{{ ansible_facts['user_uid'] }}"
    group: "{{ ansible_facts['user_gid'] }}"
    mode: 0644
  with_items:
    - gitconfig
    - gitignore
