# Copyright 2017-2019 Sébastien Wilmet <sebastien.wilmet@gmail.com>
# SPDX-License-Identifier: GPL-3.0-or-later
---
# Installs the EPEL package repository, containing a lot more packages, but not
# officially/fully supported by Red Hat.
- name: install epel-release
  package: name=epel-release state=present
